// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWkWEDaOaDsPpi8hoxqsNCNLehjFdRMVs',
    appId: '1:913974419645:web:f91975141338e3a16c57d4',
    messagingSenderId: '913974419645',
    projectId: 'flfire1demo',
    authDomain: 'flfire1demo.firebaseapp.com',
    storageBucket: 'flfire1demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ-rdY5BBZ83_v8qGtXa37PeFmxPy35ok',
    appId: '1:913974419645:android:39cbaf80145d0e9f6c57d4',
    messagingSenderId: '913974419645',
    projectId: 'flfire1demo',
    storageBucket: 'flfire1demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp7HysNZGnaJANz-CIV6JU4OGoP88nS0Q',
    appId: '1:913974419645:ios:451c205e48a8aaa76c57d4',
    messagingSenderId: '913974419645',
    projectId: 'flfire1demo',
    storageBucket: 'flfire1demo.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp7HysNZGnaJANz-CIV6JU4OGoP88nS0Q',
    appId: '1:913974419645:ios:451c205e48a8aaa76c57d4',
    messagingSenderId: '913974419645',
    projectId: 'flfire1demo',
    storageBucket: 'flfire1demo.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWkWEDaOaDsPpi8hoxqsNCNLehjFdRMVs',
    appId: '1:913974419645:web:e5ffae8df0126d386c57d4',
    messagingSenderId: '913974419645',
    projectId: 'flfire1demo',
    authDomain: 'flfire1demo.firebaseapp.com',
    storageBucket: 'flfire1demo.appspot.com',
  );
}
